### PR TITLE
Adjust installation instructions

### PR DESCRIPTION
**Pull request by seifferth**
If you install joeynmt via `pip3 install .` rather than `python3 setup.py install` there are two main benefits:

- Easy local installation using the `--user` flag
- Requirements are handled automatically by pip, removing an extra step from the process.

### CODE REVIEW

**Comment by juliakreutzer** [comment]
Cool, thanks!

**Comment by juliakreutzer** [comment]
Would you mind changing it in the [docs](https://github.com/joeynmt/joeynmt/blob/master/docs/source/install.rst) as well?

**Comment by seifferth** [comment]
Done.

**Comment by juliakreutzer** [comment]
Perfect, thanks so much!

**Pull request merged**
