### PR TITLE
Skip tests after training

### PR DESCRIPTION
**Pull request by sjarmero**
The default behavior of JoeyNMT is to test an engine after the training is finished. However, some users may want to test it later. 

The `--skip_test` argument is added. This argument prevents the test phase from being launched after the training finishes.

### CODE REVIEW

**Review by juliakreutzer — APPROVED** [review]
Good idea. Thanks!

**Comment by juliakreutzer** [comment]
@sjarmero could you please merge the __main__.py file? then we can merge the PR :) thanks!

**Comment by sjarmero** [comment]
File merged!

**Comment by juliakreutzer** [comment]
Thanks!

**Pull request merged**
