### PR TITLE
Torchtext, Torch and Numpy version upgrades.

### PR DESCRIPTION
**Pull request by Freshia**
Updated torchtext version to version 0.9.0, and consequently updated pytorch version to match the updated torchtext version, and updated numpy to match the updated pytorch version.
Changed torchtext imports to match legacy, as per the new version's release notes.

### CODE REVIEW

**Comment by juliakreutzer** [comment]
Hi @Freshia,
thanks so much and welcome to the JoeyNMT contributors club :sunglasses:

The reason why travis is failing is because ti doesn't load the right versions: Try `if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html; fi` in `.travis.yml`.

This line would also need to get updated in the README: `If you want to use GPUs add: `pip install torch==1.8.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`, for CUDA v10.1.` and `**Warning!** When running on *GPU* you need to manually install the suitable PyTorch version (1.8) for your [CUDA](https://developer.nvidia.com/cuda-zone) version.`

Could you also change the release version number? In this way we'll make clear that this version has new requirements: `release = '1.3'` in `/docs/source/conf.py` and `version='1.3',` in `setup.py`. 

I tested your code on colab (Python 3.7) and locally under Python 3.8 and it worked well :+1: :100:

**Comment by Freshia** [comment]
> Hi @Freshia,
> thanks so much and welcome to the JoeyNMT contributors club 😎
> 
> The reason why travis is failing is because ti doesn't load the right versions: Try `if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html; fi` in `.travis.yml`.
> 
> This line would also need to get updated in the README: `If you want to use GPUs add: `pip install torch==1.8.0+cu101 -f [https://download.pytorch.org/whl/torch_stable.html`](https://download.pytorch.org/whl/torch_stable.html%60), for CUDA v10.1.`and`**Warning!** When running on _GPU_ you need to manually install the suitable PyTorch version (1.8) for your [CUDA](https://developer.nvidia.com/cuda-zone) version.`
> 
> Could you also change the release version number? In this way we'll make clear that this version has new requirements: `release = '1.3'` in `/docs/source/conf.py` and `version='1.3',` in `setup.py`.
> 
> I tested your code on colab (Python 3.7) and locally under Python 3.8 and it worked well 👍 💯

Hi @juliakreutzer ! 

Thanks! Let me work on it :)

**Comment by Freshia** [comment]
Seems Travis build did not run for the latest commit. Build also failed even with the updates to the .travis.yml file :(. 
Any idea why @juliakreutzer ?

**Comment by juliakreutzer** [comment]
Hmm, I'm not sure why that build didn't even run. Could you try setting the python version to 3.8?

**Comment by Freshia** [comment]
> Hmm, I'm not sure why that build didn't even run. Could you try setting the python version to 3.8?

That fixed it! :)

**Comment by juliakreutzer** [comment]
Hoorray! :D thanks!! :100:

**Pull request merged**
