### PR TITLE
I noticed some version compatibility issues when trying to install joeyNMT in a new enviroment with the currently specified requirements. 

### PR DESCRIPTION
**Pull request by B-Czarnetzki**
…e it seems the most stable for the current joeyNMT build

### CODE REVIEW

**Comment by B-Czarnetzki** [comment]
Torch version 1.7.0 gave me a segmenation fault 
and e.g using torch version 1.5.0 doesn't work with torchtext version 0.7.0 but it works with version 0.4.0. 
So until this maybe gets worked out in more detail i thought this might prevent some pain for new people trying to install joeynmt.

**Comment by may-** [comment]
Info (especially for @juliakreutzer @bastings)
I also got segmentation fault at `import torchtext` with
- torch 1.7.0 + torchtext 0.7.0

I don't encounter this problem with either
- torch 1.6.0 + torchtext 0.7.0 or
- torch 1.7.0 + torchtext 0.8.0

I keep getting the warning like 
```
UserWarning: BucketIterator class will be retired soon and moved to torchtext.legacy. [...]
UserWarning: Batch class will be retired soon and moved to torchtext.legacy. [...]
```
in both above two settings, but joeynmt training (transformer_iwslt14_deen, in particular) is running without problem, so far.

I personally use joeynmt in torch 1.7.0 + torchtext 0.8.0 environment.  
(tested on CUDA 10.2 only)

**Comment by juliakreutzer** [comment]
Thanks a lot @B-Czarnetzki  and @may- !

**Comment by juliakreutzer** [comment]
I'll merge the 1.6.0 version for now, but I guess we'll have to revisit this in the future.

**Pull request merged**
