### PR TITLE
[transformer_layers] Missing dropout parameter passes to PositionwiseFeedForward layers

### PR DESCRIPTION
**Pull request by neccam**
The dropout parameters were not being passed to the PositionwiseFeedForward layers hence it was constantly on the default 0.1 value

### CODE REVIEW

**Comment by neccam** [comment]
There might be something wrong with the utest as the only change I did was to pass the dropout kwarg to the pwff layer.

**Comment by juliakreutzer** [comment]
Hi @neccam, thanks so much for spotting this! :muscle: 
The test fails because it was run with a dropout of 0.1 (default) before, while now it is using dropout of 0 (specified in test). Can you please adjust the expected test values accordingly (either set test dropout to 0.1 or change the expected output)?

**Comment by neccam** [comment]
> Hi @neccam, thanks so much for spotting this! 
> The test fails because it was run with a dropout of 0.1 (default) before, while now it is using dropout of 0 (specified in test). Can you please adjust the expected test values accordingly (either set test dropout to 0.1 or change the expected output)?

Done! 

not getting a requirement error though.

> error: wrapt 1.12.0 is installed but wrapt==1.11.* is required by {'astroid'}
> The command "python setup.py install" failed and exited with 1 during .

**Comment by juliakreutzer** [comment]
Thanks so much! Much appreciated.

The requirement error is unfortunate. Can you try explicitly adding 'wrapt==1.11' to the requirements?

**Comment by juliakreutzer** [comment]
Ok, so the dependency issue is fixed now, but there's one more test to adapt in the decoder.

**Comment by juliakreutzer** [comment]
Could you please fix the test accordingly and make a new PR with it? [Here](https://travis-ci.com/joeynmt/joeynmt/builds/150592968) is the test which failed.

**Comment by neccam** [comment]
Sorry the delay in this. I was focusing on the ECCV deadline, but you appearntly did it already :-)

**Comment by juliakreutzer** [comment]
Hi @neccam, hope it went well with the deadline! :sunglasses:  
We merged it but then had to revert it because the decoder test failed. I cannot re-open this PR even though it's been unmerged. Could you please re-open it in another PR? Sorry for the chaos!

**Comment by neccam** [comment]
No worries :) I will re-open another PR and fix all the decoder tests.

**Comment by juliakreutzer** [comment]
Thanks so much!

**Comment by neccam** [comment]
Done :) 
https://github.com/joeynmt/joeynmt/pull/87

**Pull request merged**
