### PR TITLE
Change the way sources and targets are specified in yaml

### PR DESCRIPTION
**Pull request by seifferth**
# Reasoning

Datasets are currently configured by specifying both a *base path* for train, dev and test as well as extensions both for *src* and *trg*. While this seems to be in line with the way things are done in torchtext, it does (imho) not provide much flexibility when it comes to naming data files. It also prevents the possibility of specifying both *src* and *trg* for some datasets, while specifying only *src* for others.

While the changed syntax proposed below is implemented by stretching the calls to torchtext quite a bit (i. e. `path` is set to the empty string and the actual, individual paths are passed to torchtext as `exts`; see commit 3a7da88), it allows for more expressive yaml-configuration. I also like to think it is a more straightforward approach to configuring datasets.

An immediate benefit of the new syntax is that it allows to distinguish two cases of missing test-targets. In one case the testset does not contain targets and a monodataset should be used. In the other case the testset is supposed to contain targets but the file is somehow missing. The most appropriate way to handle the latter case would probably be throwing a `FileNotFoundError`. The new configuration syntax proposed below allows to make that distinction.

Please understand this pull request as a mere proposal and feel free to reject it in case you feel consistency with torchtext's way of handling datasets is more important to you.

# Summary of changes

Previous yaml configuration syntax for datasets was as follows:

    data:
        src: "src_extension"
        trg: "trg_extension"
        train: "path/to/train"
        dev: "path/to/dev"
        test: "path/to/test"

This does not offer much flexibility when it comes to naming src and trg files or configuring MonoDatasets. The new configuration syntax is as follows:

    data:
        train:
            src: "path/to/train.src_extension"
            trg: "path/to/train.trg_extension"
        dev:
            src: "path/to/dev.src_extension"
            trg: "path/to/dev.trg_extension"
        test:
            src: "path/to/test.src_extension"
            trg: "path/to/test.trg_extension"

In case the testset does not contain any targets, for example, the corresponding field can simply be omitted without affecting the fact that both train and dev do have targets:

    data:
        train:
            src: "path/to/train.src_extension"
            trg: "path/to/train.trg_extension"
        dev:
            src: "path/to/dev.src_extension"
            trg: "path/to/dev.trg_extension"
        test:
            src: "path/to/test.src_extension"
            # Note that the trg field is missing

### CODE REVIEW

**Comment by bastings** [comment]
Thank you @seifferth ! What would happen to existing models if we merge this? Is there a way to keep existing models/configs working?

**Comment by seifferth** [comment]
Existing models should not pose any problem, since this pull request
doesn't include any changes to the model itself. Existing configs would
break, however.

It should be fairly easy to detect whether a configuration file uses
the old or new configuration syntax though. The old syntax includes
values for `["data"]["src"]` and `["data"]["trg"]` while the new one
doesn't. One could handle old config files in one of three ways:

- Silently rewrite the configuration internally to conform to the
  new syntax
- Raise an exception or issue a warning asking to upgrade the config file
- Combine both approaches

Rewriting the configuration internally would probably be slightly more
convenient but comes at the price of reduced code cleanliness. Simply
throwing an exception could be implemented with minimal overhead in code,
but it would be more annoying to users. I myself would still prefer
the second option though, since code cleanliness is one of joeynmt's
major goals.

**Comment by seifferth** [comment]
Existing models should not pose any problem, since this pull request doesn't include any changes to the model itself. Existing configs would break, however.

It should be fairly easy to detect whether a configuration file uses the old or new configuration syntax though. The old syntax includes values for `["data"]["src"]` and `["data"]["trg"]` while the new one doesn't. One could handle old config files in one of three ways:

- Silently rewrite the configuration internally to conform to the new syntax
- Raise an exception or issue a warning asking to upgrade the config file
- Combine both approaches

Rewriting the configuration internally would probably be slightly more convenient but comes at the price of reduced code cleanliness. Simply throwing an exception could be implemented with minimal overhead in code, but it would be more annoying to users. I myself would still prefer the second option though, since code cleanliness is one of joeynmt's major goals.

**Comment by bastings** [comment]
I'd say let's go for code cleanliness and simply update the configs and docs. I think you already updated the configurations, but could you also update the docs? (See docs/ folder). I think there are a few places where the old config is used: https://joeynmt.readthedocs.io/

After this we can merge! :-)

**Comment by seifferth** [comment]
I'm glad you like the changes :)

I already updated the example given in the tutorial in commit 2d7ace4. As far as I can see, this is the only part in the docs that is affected; Apart from the source listings, of course, but I guess those are generated automatically.

While skimming through the docs once more, I found some other files that are affected by these changes, which I didn't think about before. You might want to double-check the commits ec4c0ff and bbdd2cc to see if I got it right.

**Comment by seifferth** [comment]
Just a quick follow-up. I believe I updated all the relevant parts in the documentation. Did I miss something?

**Comment by bastings** [comment]
I think this is it, thanks! 👍

**Comment by bastings** [comment]
I'm closing this for now since we still haven't planned to merge it. We probably will remove the dependency on torch text in the future, too. We'll keep this around and if we need this functionality we'll dig it up. Thanks anyway for all the effort!

**Pull request closed without merging**
