### PR TITLE
unittest for nbest prediction

### PR DESCRIPTION
**Pull request by may-**
unittest for nbest prediction

(see discussion in #145)

Note: testing prediction is a bit tricky because we don't have a trained model for unittest. Predictions from an untrained model are completely random, so I only checked whether 1-best hypotheses (without nbest index resorting) match 0th of 5-best hypotheses (with nbest index resorting).

### CODE REVIEW

**Comment by sjarmero** [comment]
I see you already flattened `sort_reverse_index` here, thanks!

**Comment by may-** [comment]
@sjarmero if you have any concerns, or if you come up with a better solution, please don't hesitate to edit this. Thanks again for your effort!

**Comment by sjarmero** [comment]
I've run the tests locally and they're working fine for me. Sorry if I'm being finicky, but I usually find loops easier to read than generators when more than one loop is present. Something like this:

```
for _, ix in enumerate(reverse_indexes):
    for n in range(0, n_best):
        sort_reverse_index.append(ix * n_best + n)
```

Anyway, the generator is just fine, I don't think it's that hard to read. Thanks again for your changes!

**Comment by may-** [comment]
I assume you mean [list comprehension](https://docs.python.org/3/howto/functional.html#generator-expressions-and-list-comprehensions), don't you? yeah, nested for-loops would be easier to understand. more importantly, we need to comment there what we actually mean with those for-loops (i.e. why `* n_best` needed etc.), I guess. I'm still thinking what should I write there...

Let's wait for @juliakreutzer 's code review :)

**Comment by sjarmero** [comment]
Oh, sorry, yeah, I meant list comprehension. If I had to choose, I would write the nested for-loops. Let's wait for Julia's opinion and we'll discuss this further

**Review by juliakreutzer — APPROVED** [review]
This looks great! Thank you so much @may- . I think it's fine that it is not a pretrained model, as long as it's deterministic.

**Comment by juliakreutzer** [comment]
Thank you, you two are awesome!! 😊 @sjarmero I agree with your preference for loops over nested list compréhensions, especially in this case. @may- it took me a while to understand, thank you for coding it up so compactly and neatly! 
I have one suggestion that could help: how about packing the resorting in its own function? We're not using it anywhere else, but that would allow us to test it independently and with the test users can also understand it better. What do you think?

**Comment by may-** [comment]
I separated this into a function. what do you think now, @sjarmero and @juliakreutzer ?
thanks you guys for your great idea!

**Comment by sjarmero** [comment]
I love it! Very well documented. I've run `pytest` and I've actually translated some sentences with the WMT17 en-de model, and everything looks good to me

**Comment by juliakreutzer** [comment]
Thank you so much! 🎉

**Pull request merged**
