### PR TITLE
Bug fixes related to issue #144

### PR DESCRIPTION
**Pull request by sjarmero**
I've changed the `assert` to @may-'s proposal:

```
assert len(sort_reverse_index) == batch.nseqs
```

About the second issue, I'm checking if `attention_scores` is None or empty before appending. That should leave `valid_attention_scores` as an empty array when `attention_scores` is None.

### CODE REVIEW

**Comment by may-** [comment]
@sjarmero,

thank you for your quick reaction. I still have a few questions.

1) I'm not sure, but isn't it like this?
```python
for i, ix in enumerate(reverse_indexes):
    for n in range(0, n_best):
        sort_reverse_index[i].append(ix*n_best + n)
```
or in one-line:
```python
sort_reverse_index = [[ix*n_best + n for n in range(n_best)] for i, ix in enumerate(reverse_indexes)]
```
as far as I understand, `output` from run_batch is a 2D numpy array in shape of (batch.nseqs * n_best, max_output_len). For example, if batch.nseqs = 2, n_best = 3 and max_output_len = 100, then output has shape (6, 100). And it looks like:
```
[
 [1- best of seq A],
 [2- best of seq A],
 [1- best of seq B],
 [2- best of seq B],
 [1- best of seq C],
 [2- best of seq C]
]
```
Let's say `reverse_indexes` = [1, 0, 2], then `sort_reverse_index` should be [[2, 3], [0, 1], [4, 5]], shouldn't it? your current implementation without `*n_best` returns [[1, 2], [0, 1], [2, 3]], instead, in this specific case.  
maybe you are right, I just overlook something important... Please correct me, if I'm wrong.

---
2) As @juliakreutzer said, I also don't think we should store all nbest attention scores. Moreover, `attention_scores` returned from `run_batch` is not None only if the architecture is RNN and the decoding method is greedy, so never happens together with n_best > 1, because n_best is currently only supported in beam decoding. That is, we could keep the original code for `attention_scores` (outside for-loop), couldn't we?
```python
for reverse_index in sort_reverse_index:
    all_outputs.append(output[reverse_index])
valid_attention_scores.extend(attention_scores[reverse_indexes] if attention_scores is not None else [])
```
How do you think?

**Comment by sjarmero** [comment]
You're right about the first issue, I guess I didn't understand quite right what the original code was doing. I'm changing the code to include your proposal.

About the second issue, I'll test my code as soon as I have some time to do so and I'll let you know.

**Comment by sjarmero** [comment]
You were right, I changed the code to your proposed solution

**Comment by juliakreutzer** [comment]
Thanks so much for implementing the suggested changes @sjarmero! Did you get a chance to test your code?

**Comment by sjarmero** [comment]
Yes, I have. I have tested a small RNN model with greedy decoding and attention plots look good to me. I have also generated attention plots for the same dataset using the previous version of JoeyNMT, just to compare outputs, and it looks good too.

**Comment by may-** [comment]
sorry, I'm still confused, how the nested `reverse_indexes` re-sorts the index of `all_outputs`.  Do you get the same sentence order as src in all n_best output files?   

how about flattning the `sort_reverse_index` and keep other parts unchanged? something like:

```python
    for batch in valid_iter:
        # sort batch now by src length and keep track of order
        sort_reverse_index = batch.sort_by_src_length()

        if n_best > 1:
            sort_reverse_index = [ix*n_best + n
                                  for i, ix in enumerate(sort_reverse_index)
                                  for n in range(n_best)]
            assert len(sort_reverse_index) == batch.nseqs * n_best

        # run as during training to get validation loss (e.g. xent)
        if compute_loss and batch.trg is not None:
...
```

in the current version, `all_outputs` is a nested list and flattened here
https://github.com/joeynmt/joeynmt/blob/40a1565aaea96c698563c9b30c9667a623816196/joeynmt/prediction.py#L149-L154

but with a flattened `sort_reverse_index`, it can be back to the original
```python
    # decode back to symbols
    decoded_valid = model.trg_vocab.arrays_to_sentences(arrays=all_outputs,
                                                        cut_at_eos=True)
```

First, flattening a nested list is computationally heavy, as the input size grows. it is applied to valid/test set, so the input is maybe not so large, but we should avoid it if possible. so, we can activate the new n_best functionality only if n_best > 1 and keep unchanged when n_best == 1, i.e. in validation during training. 

Second, minimalism is a core of philosophy of joeynmt, we try to keep the code as simple as possible. it would be easier to understand even for new contributors who will edit this part in future, without knowing our discussion here.

how do you think?

**Comment by sjarmero** [comment]
The actual first version of that code was a flattened `sort_reverse_index`, I changed it because of this change request: https://github.com/joeynmt/joeynmt/pull/139#discussion_r585231614

I don't mind making it a flat list again

**Comment by juliakreutzer** [comment]
Thanks for the reminder about efficiency @may- ! You are right that a flat list is more efficient. I was mostly concerned about users who could potentially misinterpret the output. I'm fine with a flat list, it just needs to be documented well, i.e. in docstrings, and perhaps a few in-line comments.

Would it be possible to write a test that ensures that 1-best decoding returns the same output as the first element of n-best decoding? That might help reducing the risk for bugs in the future, and also serves as an example for documentation.

**Comment by may-** [comment]
I totally agree with @juliakreutzer ! I'll try to write a unit test for nbest outputs.

**Comment by sjarmero** [comment]
Ok @may- thanks for writing the unit tests. I'll change the code so that it uses a flat list

**Comment by juliakreutzer** [comment]
I'll merge it now so that bug is fixed (kind of urgent). Thanks @may- for writing a test, and thanks @sjarmero for flattening it again :D see you in another PR!

**Pull request merged**
