### PR TITLE
feat(data): allow overriding `collate_fn` without overriding `make_iter`

### PR DESCRIPTION
**Pull request by AmitMY**
Natural continuation of #189 
Not necessary, just nicer imo.

- the `make_iter` method only calls `make_data_iter`, which is a bit redundant and obfuscated.
- the `collate_fn` was also separate out of the class, and while one can override `make_iter` in order to specify a different `collate_fn`, it requires less code and understanding to only modify `collate_fn`

### CODE REVIEW

**Comment by may-** [comment]
yes, I like this very much! Thank you 👍

**Comment by may-** [comment]
@AmitMY just a question. don't you need `**kwargs` in `make_iter()` any more? Wasn't it the purpose of this change in the first place??

**Comment by AmitMY** [comment]
The purpose was for the method to be override-able, the `**kwargs` was just a shorthand to pass the parameters.
Because the `training` and `prediction` code both call this method with a specific list of parameters, I don't really see why there would also be a need for `**kwargs`, but I can add it!

**Comment by may-** [comment]
@AmitMY well, I feel the overriding the class is even nicer. `**kwargs` might be misleading for the users who don't know our discussion here. The current code can imply that they should override instead of giving custom var, so I really like it. Thanks for your cooperation, again 😄 

@juliakreutzer Let's accept this before we update to v2.1.0 in PyPI!

**Review by may- — APPROVED** [review]

**Comment by may-** [comment]
@AmitMY 

Since `collate_fn` is also a method of the class, we don't have to pass the class members, I guess. How about this?
```python
# in def make_iter()
return DataLoader(
    self,
    batch_sampler=batch_sampler,
    collate_fn=partial(self.collate_fn, pad_index=pad_index, device=device),
    num_workers=num_workers,
)
```
and
```python
def collate_fn(
    self,
    batch: List[Tuple],
    pad_index: int = PAD_ID,
    device: torch.device = CPU_DEVICE,
) -> Batch:

    def _is_valid(s, t, has_trg):
        # pylint: disable=no-else-return
        if has_trg:
            return s is not None and t is not None
        else:
            return s is not None

    batch = [(s, t) for s, t in batch if _is_valid(s, t, self.has_trg)]
    src_list, trg_list = zip(*batch)
    assert len(batch) == len(src_list), (len(batch), len(src_list))
    assert all(s is not None for s in src_list), src_list
    src, src_length = self.sequence_encoder[self.src_lang](src_list)

    if self.has_trg:
        assert all(t is not None for t in trg_list), trg_list
        trg, trg_length = self.sequence_encoder[self.trg_lang](trg_list)
    else:
        assert all(t is None for t in trg_list)
        trg, trg_length = None, None
    return Batch(
        src=torch.tensor(src).long(),
        src_length=torch.tensor(src_length).long(),
        trg=torch.tensor(trg).long() if trg else None,
        trg_length=torch.tensor(trg_length).long() if trg_length else None,
        device=device,
        pad_index=pad_index,
        has_trg=self.has_trg,
        is_train=self.split == "train",
    )
```
what do you think?

**Comment by AmitMY** [comment]
I like your suggestion very much, and have implemented it!

**Comment by may-** [comment]
Thank you for your quick reaction!! 😃

**Pull request merged**
